
name: CI

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Run the CV script
        uses: docker://pandoc/latex
        with: 
          entrypoint: sh
          args: cv.sh
          workdir: /github/workspace/
          
      - name: Remove gitignore for pages
        run: rm -f .gitignore
          
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

